name: Collect Latest Issues
on: workflow_dispatch

jobs:
  findIssues:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: octokit/graphql-action@v2.x
        id: mariner_issue_collector
        with:
          query: |
            query {
              search(query:"repo:facebook/react repo:mui-org/material-ui repo:elastic/elasticsearch repo:pandas-dev/pandas repo:typescript-eslint/typescript-eslint repo:facebook/jest repo:gatsbyjs/gatsby repo:stylelint/stylelint repo:microsoft/TypeScript repo:grpc-ecosystem/grpc-gateway repo:GoogleChrome/workbox label:\"good first issue\" created:>2020-07-06 state:open", type:ISSUE, first:100){
                issueCount
                edges{
                  node{
                    ... on Issue{
                      title
                      createdAt
                      repository {
                        nameWithOwner
                      }
                      url
                    }
                  }
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo $json_output > sample-output-raw.json
          jq . sample-output-raw.json > sample-output.json
          git config --local user.email "opensource@indeed.com"
          git config --local user.name "GitHub Action test"
          git add ./sample-output.json
          git commit -m "update issues"
          git push
        env:
          json_output: ${{ steps.mariner_issue_collector.outputs.data }}
